console.log('O console funcionou corretamente.')
//"console.log()" serve para "printar" a mensagem.

var vel = 80.5
console.log(`A velocidade do seu carro é ${vel}km/h.`)
//Lembre-se de usar crase para poder usar as máscaras ("strings" com interpolação).

if (vel > 60) {
    console.log('Você ultrapassou a velocidade máxima permitida. Você foi multado!')
}

//Acima, temos uma condição simples.
console.log('Dirija sempre usando cinto de segurança.')

//A maneira como o código está organizado acima, se chama "indentação" (que pode ser entendido como "recuo").
